# Generated by Django 4.1.2 on 2022-10-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='time',
            new_name='uploaded_at',
        ),
    ]
