# Generated by Django 4.1.2 on 2022-10-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_time_filemodel_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='uploaded_at',
            new_name='time',
        ),
    ]
