# Generated by Django 4.1.2 on 2022-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_uploaded_at_filemodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
