# Generated by Django 4.1.2 on 2022-11-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_filemodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='downloads',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
