# Generated by Django 4.1.2 on 2022-11-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_filemodel_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
